### ISSUE TITLE
Scorigami on an area that was not.10-25-2020

### ISSUE THREAD

**Issue by PlazmaCube** [ACMerriman/scorigami#21]
It says that the Detroit Lions/Atlanta Falcons game was Scorigami when it was, in-fact, not. The score of 23-22 had already happened a few times. Instead, this game went to the spot that is the score 22-22 tie, which is Scorigami, but that was not the final score. I recommend you get this fixed soon because I got really excited when I thought it was scorigami when it was, in-fact, not.

Thanks

   -PlazmaCube

**Comment by ACMerriman** [comment]
Fixed the issue, but not the cause (yet). Caused by the Lions scoring a TD with no time remaining, then scoring a PAT. Personally I blame the API for marking the game as over before the teams were off the field.

**Comment by PlazmaCube** [comment]
Ahh, ok. That's a little bit of what I figured too. It can be weird when the clock says 0:00 on it. It's cool, anyways. We still got a Scorigami today
