### ISSUE TITLE
Falcons - Lions game says scorigami though it happened 12 times before.

### ISSUE THREAD

**Issue by 1ctinus** [ACMerriman/scorigami#22]

**Comment by PlazmaCube** [comment]
I saw that too. I mentioned in bugs as well how The reason there was confusion is that the square was placed at 22-22 Tie, which would be Scorigami, but the final score was 23-22, which would be a no-go. I think the machine that finds out Scorigami's is bugged (Unless Jon himself manages this.) But whatever the case, I certainly got excited when it said Scorigami, and wes then disappointed when it was not.

**Comment by ACMerriman** [comment]
same as https://github.com/ACMerriman/scorigami/issues/21
