### ISSUE TITLE
Feature request: show Scorigamis from a season

### ISSUE THREAD

**Issue by redbrain** [ACMerriman/scorigami#23]
Consider adding the option to select/highlight all the Scorigamis from a select season(s) or time range.

**Comment by ACMerriman** [comment]
There already exists the option to highlight the Scorigamis by year by selecting First Game from the dropdown menu at the top of the page

**Comment by haltman-at** [comment]
Could this be reopened?  Currently it does it by *year*, not *season*.  I think that if you select e.g. 2020, it should show the 2020 season, not the 2020 year.  Basically you could just do this as, if year n is selected, it shows the second half of year n and the first half of year n+1.  Or something like that.
