### ISSUE TITLE
with the website down, no new instances with the board can be created because the database file is copied from the dead server.

### ISSUE THREAD

**Issue by 1ctinus** [ACMerriman/scorigami#29]

**Comment by PlazmaCube** [comment]
Is McMerriman there? Are they aware? This is super important I hope the site gets fixed soon. If not I've already printied out a physical up-to-date card but still, preseason is already over, the season starts in 3 days, why isn't this fixed yet???

**Comment by leerob** [comment]
Yeah, if you can dump the PG database file somewhere, we can host it elsewhere and get it back up

**Comment by ACMerriman** [comment]
Alright guys, I don't want to talk about how simple the fix was compared to how much work I put into it, but the site is back up.

**Comment by leerob** [comment]
Thank you 😄

**Comment by PlazmaCube** [comment]
Thank you soooo much! I almost marked the site off as "Unusable."
