### ISSUE TITLE
Cross-reference "NFL_Scorigami" Twitter bot source code

### ISSUE THREAD

**Issue by mzmcbride** [ACMerriman/scorigami#4]
https://twitter.com/NFL_Scorigami is neat, but I'm not sure where its source code is. If someone knows, cross-referencing that information in this repository's README would be really nice.

**Comment by ACMerriman** [comment]
I talked to the guy that made the bot, he gave me a very brief (tweet-length) rundown of how it works (you can see the conversation [here](https://twitter.com/Blackcat008/status/917257576974372866)). 

Long story short, I would like to add a feature like that, but I have no idea how he made it and I'm too afraid to dig further.

**Comment by mzmcbride** [comment]
Ah, okay. Thanks for the info. I searched around for "dpmattingly" and "scorigami" on GitHub a bit, but didn't find much. There's <https://github.com/aphung/scorigami> for what it's worth.

I hadn't seen the conversation you linked, but I did find these messages:

* https://twitter.com/NFL_Scorigami/status/911089531130077184
* https://twitter.com/NFL_Scorigami/status/911090864826466304
* https://twitter.com/NFL_Scorigami/status/911091854921285632
* https://twitter.com/NFL_Scorigami/status/911099233645637632

This is all pretty off-topic, though. Please feel free to close this issue if there's nothing actionable here.
