### ISSUE TITLE
Preseason Games are not Counted

### ISSUE THREAD

**Issue by WJP2003** [ACMerriman/scorigami#6]
I checked if preseason games show up in the scorigami app, they appear not to. For example, on 3 August 2017, the Dallas Cowboys won versus the Arizona Cardinals 20-18; however the app says that the last time an 20-18 score happened was 23 January 2016 when the Denver Broncos won vs the New England Patriots (crazy right?) 20-18.

I bring this up since the Denver Broncos won vs the Arizona Cardinals 30-2 in the 2017 preseason, and I did not see the 30-2 box lit up. If it is possible to fix this, please do! Thanks!

**Comment by ACMerriman** [comment]
This is intentional. Only Regular and Post season games are counted since preseason games are more-or-less meaningless.

**Comment by WJP2003** [comment]
Oh. Well I still thought you could at least add a "preseason mode" or something to toggle them. Preseason games don't really matter but scorigami can still happen in them. Thanks for responding so quickly!

**Comment by WJP2003** [comment]
If for example the absurd defensive 1-pt safety were to happen in a preseason game, it's hard not to take note of it.

**Comment by ACMerriman** [comment]
It is certainly possible, but it would require a sizable overhaul of the system I have set up, plus I wouldn't be able to accurately test it until the actual preseason. Neither of these things completely disqualify the idea, but they do demotivate me. However I can only find preseason records dating back to 1983, so even if I were to implement it, it would never be accurate, which does disqualify it in my eyes.

**Comment by WJP2003** [comment]
Well that's unfortunate. I'd be OK with it only doing preseason games since when you can get records of them, but could you please let me know where you got those preseason scores? I might be able to write a script myself to get the data or put it in Google Sheets for easy access or something. Thanks for letting me know!

**Comment by ACMerriman** [comment]
https://www.pro-football-reference.com/years/2017/preseason.htm

change 2017 to whatever year, all the way down to 1983

**Comment by WJP2003** [comment]
OK, thanks.

**Comment by WJP2003** [comment]
I dug through the code and saw that the updateData() function ignores preseason games; you could store the seasonType directly into the data file and use a toggle on the page to enable/disable them. I would test this myself but I don't know how to go about importing old preseason game data (like the 30-2 game). The only thing I think would be difficult is importing the old data-- as far as I know if you import preseason games from 2018 onwards you won't have to change your system very much if at all. At the moment I'm writing a script to download all of the preseason scores since 1983 and converting them to the format used in http://scorigami.herokuapp.com/data.

**Comment by ACMerriman** [comment]
It's not quite that simple. You would have to store all of the relevant data to fill out the info box, effectively almost doubling the data you have to maintain

**Comment by WJP2003** [comment]
If you're using the "gameDate": "9/9/1999" thing in the JSON for the date, I've got that covered, and I'm getting as much information as I can. I've gotten the score, date, and teams involved from pro-football-reference; if there's any more data I need let me know. Also, I'm getting all the data from 1983 till now, but since the NFL's feed thing does preseason games as also I think it'll work with those too. I'm just getting old games now.

**Comment by WJP2003** [comment]
I got it to work and this is a sample output:

```
{
    "season": 1983,
    "seasonType": "PRE",
    "week": 4,
    "gameScores": [
        {
            "gameSchedule": {
                "season": 1983
                "seasonType": "PRE",
                "week": 4
                "gameDate": "8/31/1983"
                "homeDisplayName": "Arizona Cardinals"
                "visitorDisplayName": "*Denver Broncos*"
            }
        
}
```
If you need more info let me know.

**Comment by ACMerriman** [comment]
You also need the scores

**Comment by WJP2003** [comment]
Oh yeah stupid me

**Comment by WJP2003** [comment]
Here's one that has the scores this time around. I couldn't get quarter by quarter info but that shouldn't matter, right?
```
      {
            "gameSchedule": {
                "season": 1983
                "seasonType": "PRE",
                "week": 4
                "gameDate": "8/31/1983"
                "homeDisplayName": "Arizona Cardinals"
                "visitorDisplayName": "*Denver Broncos*"
                "visitorTeamScore": {
                    "pointTotal": 2
                }
                "homeTeamScore": {
                    "pointTotal": 30
                }
            }
        }
```

**Comment by ACMerriman** [comment]
No, the database doesn't care what the score at any point in the game but the end.

**Comment by WJP2003** [comment]
All right so here's the file of every preseason game ending since 1983:

**Comment by WJP2003** [comment]
I pressed the wrong button to close this. Anyway, here's that file: 
[dump.json.txt](https://github.com/ACMerriman/scorigami/files/1633765/dump.json.txt)

**Comment by ACMerriman** [comment]
Nice! You'll have to mess with the parser a bit to force things through, but that's all of the data you'll need to track

**Comment by WJP2003** [comment]
All right cool! Those are all of the old ones from 1983-2017 which I imagine isn't too difficult to import into your database. When it comes to the 2018+ preseason games, AFAIK the data from NFL's feeds is the same; you just need to remove this if statement (line 67 in server.js):
```
if (data.seasonType === "REG" || data.seasonType === "POST")
```
and it'll record future preseason games.

**Comment by ACMerriman** [comment]
More or less, yeah. If you intend to keep preseason as an option instead of the default, you'll have to add checks later on to keep preseason separate.

**Comment by WJP2003** [comment]
All right, cool. I looked through the code and made it so that there is a "score" element so it can be parsed with the same parser:

```
        {
            "gameSchedule": {
                "season": 1985
                "seasonType": "PRE",
                "week": 2
                "gameDate": "8/11/1985"
                "homeDisplayName": "*Kansas City Chiefs*"
                "visitorDisplayName": "Cincinnati Bengals"
                "score": {
                    "visitorTeamScore": {
                        "pointTotal": 35
                    }
                    "homeTeamScore": {
                        "pointTotal": 27
                    }
                }
            }
        }
```

P.S. I noticed in the code the variable "aCompleteF***ingMiracleHasHapppened"

**Comment by WJP2003** [comment]
The only big-ish problem is the "gameLink" since these preseason games... don't have links.

**Comment by ACMerriman** [comment]
You could just have it link to the list of preseason games where you got the data from originally

aCompleteFuckingMiracleHasHappened is a case that will likely never be true (hence the name), but has actually proven to be very useful in testing since it allows me to just dump a bunch of fake scores on some point in the chart and it handles them beautifully

**Comment by WJP2003** [comment]
Good idea for the link, might be a bit awkward though with the "see all 7 games" or whatever link. And I see what aCompleteFuckingMiracleHasHapppened is for now. (and yes in the source code there are 3 p's in Happpened)

**Comment by ACMerriman** [comment]
[https://github.com/ACMerriman/scorigami/commit/ad962c571bf58d525d50140e76732c8918e2d11b](No it doesn't)

**Comment by ACMerriman** [comment]
[No it doesn't](https://github.com/ACMerriman/scorigami/commit/ad962c571bf58d525d50140e76732c8918e2d11b)

**Comment by WJP2003** [comment]
Here's a fixed file (some minor errors): 
[dump.json](https://github.com/ACMerriman/scorigami/files/1635998/dump.json.txt)

**Comment by WJP2003** [comment]
To add to this, is the Pro Bowl counted (as it is soon)? Generally it's pretty high scoring, and might go deeper into the "scoring arctic" where both teams score a ton.

**Comment by ACMerriman** [comment]
It isn't. I am not tracking any exhibition games.

**Comment by WJP2003** [comment]
OK.
